# Laboratorio de regresión - 4

|                |   |
:----------------|---|
| **Nombre**     | Diana Fernanda Barbosa Dueñas  |
| **Fecha**      | 08/02/2026  |
| **Expediente** | 756920  |

## Modelos penalizados

Hasta ahora la función de costo que usamos para decidir qué tan bueno es nuestro modelo al momento de ajustar es:

$$ \text{RSS} = \sum_{i=1}^n e_i^2 = \sum_{i=1}^n (y_i - \hat{y_i})^2 $$

Dado que los errores obtenidos son una combinación de sesgo y varianza, puede ser que se sesgue un parámetro para minimizar el error. Esto significa que el modelo puede decidir que la salida no sea una combinación de los factores, sino una fuerte predilección sobre uno de los factores solamente.

E.g. se quiere ajustar un modelo

$$ \hat{z} = \hat{\beta_0} + \hat{\beta_1} x + \hat{\beta_2} y $$

Se ajusta el modelo y se decide que la mejor decisión es $\hat{\beta_1} = 10000$ y $\hat{\beta_2}=50$. Considera limitaciones de problemas reales:
- Quizás los parámetros son ajustes de maquinaria que se deben realizar para conseguir el mejor producto posible, y que $10000$ sea imposible de asignar.
- Quizás los datos actuales están sesgados y sólo hacen parecer que uno de los factores importa más que el otro.

Una de las formas en las que se puede mitigar este problema es penalizando a los parámetros del modelo, cambiando la función de costo:

$$ \text{RSS}_{L2} = \sum_{i=1}^n e_i^2  + \lambda \sum_{j=1}^p \hat{\beta_j}^2 $$

El *L2* significa que se está agregando una penalización de segundo orden. Lo que hace esta penalización es que los factores ahora sólo tendrán permitido crecer si hay una reducción al menos proporcional en el error (sacrificamos sesgo, pero reducimos la varianza).

Asimismo, existe la penalización *L1*

$$ \text{RSS}_{L1} = \sum_{i=1}^n e_i^2  + \lambda \sum_{j=1}^p |\hat{\beta_j}| $$

A las penalizaciones *L2* y *L1* se les conoce también como Ridge y Lasso, respectivamente.

Para realizar una regresión con penalización de Ridge o de Lasso usamos el objeto `Ridge(alpha=?)` o `Lasso(alpha=?)` en lugar de `LinearRegression()` de `sklearn`.

Utiliza el dataset de publicidad (Advertising.csv) y realiza 3 regresiones múltiples:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

1. Sin penalización
2. Con penalización L2
3. Con penalización L1

¿Qué puedes observar al ajustar los valores de `alpha`?

Compara los resultados de los coeficientes utilizando valores diferentes de $\alpha$ y los $R^2$ resultantes.



In [6]:
from google.colab import files
uploaded = files.upload()

Saving Advertising.csv to Advertising.csv


In [4]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [7]:
data = pd.read_csv("Advertising.csv")

In [11]:
X = data[['TV', 'radio', 'newspaper']]
y = data['sales']

In [14]:
# Modelo sin penalización
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [15]:
lr.coef_, lr.intercept_

(array([ 0.04576465,  0.18853002, -0.00103749]), np.float64(2.938889369459412))

In [17]:
# Predicciones
y_pred = lr.predict(X)
y_pred

array([20.52397441, 12.33785482, 12.30767078, 17.59782951, 13.18867186,
       12.47834763, 11.72975995, 12.12295317,  3.72734086, 12.55084872,
        7.0322992 , 17.28512918, 10.57712073,  8.82630048, 18.43436638,
       20.81929952, 12.82365674, 23.22495716,  9.95168206, 14.16607293,
       18.10076728, 14.7405382 ,  6.4891503 , 16.5459329 ,  8.14651887,
       15.6100386 , 14.98951429, 17.05167344, 19.41053803,  9.14402389,
       21.6339338 , 11.3460929 ,  7.63888314, 18.86426829,  7.57483051,
       17.00682618, 23.40590052, 15.62347779,  9.90868103, 20.44761039,
       16.37766467, 17.2959832 , 21.59580326, 13.96385684,  8.88787996,
       15.16152314,  8.87338673, 21.7226299 , 16.26362018,  8.1681656 ,
       12.63121132,  9.33981296, 20.66297563, 19.94469957, 20.37443008,
       21.2926106 ,  8.52771254, 12.77458802, 21.89805198, 18.13348698,
        5.74215558, 22.89067208, 16.78426073, 13.21069202, 16.97773556,
        7.84904532,  9.01603163, 12.0370073 , 18.97657924, 21.10

In [20]:
r2 = lr.score(X, y)
r2

0.8972106381789522

### **Regresión con penalización L2**

In [22]:
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [30]:
n = int(len(X) * 0.7)

X_train = X[:n]
X_test = X[n:]

y_train = y[:n]
y_test = y[n:]

In [31]:
for a in [0.1, 1, 10]:
    modelo = Ridge(alpha=a)
    modelo.fit(X_train, y_train)
    pred = modelo.predict(X_test)

In [38]:
modelo.coef_, modelo.intercept_

(array([ 0.0470487 ,  0.17967605, -0.00300387]),
 np.float64(3.0452553341530066))

In [40]:
r2 = lr.score(X_train, y_train)
r2

0.8924939089912414

### **Regresión con penalización L1**

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [33]:
modelo = LinearRegression()
modelo.fit(X_train, y_train)

LinearRegression()

In [34]:
pred = modelo.predict(X_test)

In [35]:
modelo.coef_, modelo.intercept_

(array([ 0.04704868,  0.17968299, -0.00300557]),
 np.float64(3.0451422090371167))